services:
  web:
    image: server:v1
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sqlpassword
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306